/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    FHETimeCapsule: {
      address: "0x3EC8F07CE3D2E4F1876DFE4F361eA79007FE7B8e",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
          ],
          name: "CapsuleCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "unlockTime",
              type: "uint256",
            },
          ],
          name: "CapsuleCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "creatorHandle",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "unlockTimeHandle",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "isActiveHandle",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "isUnlockedHandle",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes32[]",
              name: "messageHandles",
              type: "bytes32[]",
            },
          ],
          name: "CapsuleEncryptionGranted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
          ],
          name: "CapsuleUnlocked",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
          ],
          name: "cancelTimeCapsule",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "externalEuint256[]",
              name: "encryptedMessageChunks",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "messageProofs",
              type: "bytes[]",
            },
            {
              internalType: "externalEuint64",
              name: "encryptedUnlockTimeHandle",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "unlockTimeProof",
              type: "bytes",
            },
            {
              internalType: "uint256",
              name: "unlockTime",
              type: "uint256",
            },
          ],
          name: "createTimeCapsule",
          outputs: [
            {
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getActiveCapsulesByUser",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
          ],
          name: "getEncryptedCapsuleMetadata",
          outputs: [
            {
              internalType: "eaddress",
              name: "encryptedCreator",
              type: "bytes32",
            },
            {
              internalType: "euint64",
              name: "encryptedUnlockTime",
              type: "bytes32",
            },
            {
              internalType: "ebool",
              name: "encryptedIsActive",
              type: "bytes32",
            },
            {
              internalType: "ebool",
              name: "encryptedIsUnlocked",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
          ],
          name: "getEncryptedMessage",
          outputs: [
            {
              internalType: "euint256[]",
              name: "",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getExpiredCapsulesCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
          ],
          name: "getTimeCapsule",
          outputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "unlockTimestamp",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isActive",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isUnlocked",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "messageLength",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalCapsules",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserCapsules",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
          ],
          name: "grantDecryptionAccess",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "nextCapsuleId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "capsuleId",
              type: "uint256",
            },
          ],
          name: "openTimeCapsule",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9390328,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
